# Site settings
title: Skistone Vacation Rentals
email: skistone1+info@skistonevacationrentals.com
telephone: 303-345-3213
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://dev.skistonevacationrentals.com/" # the base hostname & protocol for your site

x_username: skistonei
facebook_username: skistone1
tiktok_username: skistonei
instagram_username: skistone1

# Build settings
markdown: kramdown
